### ISSUE TITLE
How to implement SVD single rank decomposition by partial_ tucker()

### ISSUE THREAD

**Issue by filoliufei** [TaehyeonKim-pyomu/CNN_compression_rank_selection_BayesOpt#1]
In your paper, we see the performance of the proposed method in SVD. Is it implemented on the basis of Tucker decomposition? Or do you need to write separate SVD decomposition code?

**Comment by TaehyeonKim-pyomu** [comment]
The SVD experiment result was reported by a modified version of the uploaded code. I think changing my code to SVD-based CNN compression is not hard work. If you need further help, please let me know.

**Comment by filoliufei** [comment]
Hello, we are learning CNN compression based on SVD. Can you upload the modified version of the upload code(BayesOpt-based Global Optimal Rank Selection)?

**Comment by filoliufei** [comment]
Hello, we are very interested in the work of you and your team. What is the accuracy rate of SVD after decomposition and before fine tuning? Our test results show that, taking vgg19 as an example, the accuracy of SVD decomposition before fine tuning is basically 0. thank you!
